name: Build + Check + APK Stats

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Run dependencies
        run: ./gradlew :shared:dependencies :android:dependencies --stacktrace --scan


  check:
    needs:
      - pre-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: build-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Verify database schema + migration
        run: |
          ./gradlew :shared:generateCommonMainReaderDatabaseSchema
          if [[ $(git diff --stat) != '' ]]; then
            echo "\033[1;31m> \033[0m"
            echo "\033[1;31mError: Database schema changed without adding a migration. \033[0m"
            echo "\033[1;31m> \033[0m"
            exit 1
          else
            ./gradlew :shared:verifySqlDelightMigration
          fi


  build-shared:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: build-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Assemble Shared
        run: ./gradlew clean :shared:assemble --stacktrace --scan


  build-android:
    needs:
      - build-shared
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: build-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Assemble Android
        run: ./gradlew :android:assembleRelease --stacktrace --scan
      - name: Archive APKs
        run: |
          cp android/build/outputs/apk/release/*.apk release-${{ github.sha }}.apk
      - name: Upload archived assets
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-archive
          path: release-${{ github.sha }}.apk
          retention-days: 1
      - name: Push APK to assets/master
        if: github.ref == 'refs/heads/master'
        run: |
          git config user.name "Github Action"
          git config user.email "elliot.tormey@gmail.com"
          git checkout --orphan assets/master
          git rm --cached -r .
          cp -R android/build/outputs/apk/release/. assets
          git add assets
          git commit -m 'add assets from ${{ github.sha }}'
          git push -f origin assets/master


  # TODO
  # build-ios:
  #   needs:
  #     - build-shared


  apk-stats:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Download Archived binaries
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-archive
      # Manually download from branch rather than using action/checkout step so that
      # diffuse binary is the latest relative to the branch being build rather than master etc.
      - name: Download Latest assets from assets/master
        run: git fetch origin && git checkout origin/assets/master assets/

      - name: Run diffuse on APK
        run: |
          .github/bin/diffuse-0.1.0-binary.jar diff --apk assets/*.apk release-${{ github.sha }}.apk > apk-diff-${{ github.sha }}.txt
          printf "### Diffuse stats for \`$(echo ${GITHUB_BASE_REF} | cut -c1-7)\` ➡ $(echo ${GITHUB_SHA} | cut -c1-7) \n\n\`\`\`\n" > apk-pr-comment.txt && sed '/====   DEX   ====/q' apk-diff-${{ github.sha }}.txt | tac | sed "1,2d" | tac | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' >> apk-pr-comment.txt && echo "\`\`\`"  >> apk-pr-comment.txt
      - name: Add APK diff
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: apk-pr-comment.txt

      - name: Upload full diff
        uses: actions/upload-artifact@v3.1.2
        with:
          name: diff-report
          path: apk-diff-${{ github.sha }}.txt
